version: '3'

services:
  xybot:
    build: .
    container_name: xybot
    restart: unless-stopped
    ports:
      - "8080:8080"  # Web界面
      - "9000:9000"  # WechatAPI
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./plugins:/app/plugins
      - ./config:/app/config
    environment:
      - TZ=Asia/Shanghai

  redis:
    image: redis:6-alpine
    container_name: xybot-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: